/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moviebooking;
//import javax.swing.*;
//import java.awt.Image;

import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author deepa
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        setResizable(false);
        cmbLang.setSelectedItem(null);
        cmbMovie.setSelectedItem(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        SubTotal2 = new javax.swing.JPanel();
        lbCinemaName = new javax.swing.JLabel();
        lbLanguage = new javax.swing.JLabel();
        lbMovie = new javax.swing.JLabel();
        cmbLang = new javax.swing.JComboBox<>();
        cmbMovie = new javax.swing.JComboBox<>();
        LbTimeDetail = new javax.swing.JLabel();
        lbDay = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();
        cmbTime = new javax.swing.JComboBox<>();
        lbTheater = new javax.swing.JLabel();
        lbTicketPrice = new javax.swing.JLabel();
        lbAdult = new javax.swing.JLabel();
        lbChild = new javax.swing.JLabel();
        lbSnack = new javax.swing.JLabel();
        lbAdultPrice = new javax.swing.JLabel();
        lbChildprice = new javax.swing.JLabel();
        lbAdultQty = new javax.swing.JLabel();
        lbChildQty = new javax.swing.JLabel();
        cmbAdult = new javax.swing.JComboBox<>();
        cmbChild = new javax.swing.JComboBox<>();
        cmbsnack = new javax.swing.JComboBox<>();
        cmbDrink = new javax.swing.JComboBox<>();
        lbsnackQty = new javax.swing.JLabel();
        lbdrinkQty = new javax.swing.JLabel();
        cmbSnack = new javax.swing.JComboBox<>();
        cmbDrinkCmd = new javax.swing.JComboBox<>();
        lbTotalSnackAmt = new javax.swing.JLabel();
        lbExtra = new javax.swing.JLabel();
        lbSeattype = new javax.swing.JLabel();
        cmdSeat = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        lbAgeRate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbDialoug = new javax.swing.JLabel();
        cmbPayment = new javax.swing.JComboBox<>();
        payBtn = new javax.swing.JButton();
        lbFilmImg = new javax.swing.JLabel();
        lbtheaterno = new javax.swing.JLabel();
        SubTotal = new javax.swing.JButton();
        Totalamt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblMovieImage = new javax.swing.JLabel();
        lbbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SubTotal2.setOpaque(false);

        lbCinemaName.setBackground(new java.awt.Color(0, 51, 51));
        lbCinemaName.setFont(new java.awt.Font("Constantia", 3, 36)); // NOI18N
        lbCinemaName.setForeground(new java.awt.Color(255, 255, 255));
        lbCinemaName.setText("Movie Magnet");

        lbLanguage.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lbLanguage.setForeground(new java.awt.Color(255, 255, 255));
        lbLanguage.setText("Select Language:");

        lbMovie.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lbMovie.setForeground(new java.awt.Color(255, 255, 255));
        lbMovie.setText("Select Movie:");

        cmbLang.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        cmbLang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Hindi", "Marathi" }));
        cmbLang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLangActionPerformed(evt);
            }
        });

        cmbMovie.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        cmbMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMovieActionPerformed(evt);
            }
        });

        LbTimeDetail.setFont(new java.awt.Font("Constantia", 3, 18)); // NOI18N
        LbTimeDetail.setForeground(new java.awt.Color(255, 153, 153));
        LbTimeDetail.setText("Date & Showtime");

        lbDay.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lbDay.setForeground(new java.awt.Color(255, 255, 255));
        lbDay.setText("Date of show:");

        lbTime.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lbTime.setForeground(new java.awt.Color(255, 255, 255));
        lbTime.setText("Time of show:");

        cmbTime.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N

        lbTheater.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lbTheater.setForeground(new java.awt.Color(255, 255, 255));
        lbTheater.setText("Theatre No:");

        lbTicketPrice.setFont(new java.awt.Font("Constantia", 3, 18)); // NOI18N
        lbTicketPrice.setForeground(new java.awt.Color(255, 51, 51));
        lbTicketPrice.setText("Ticket Pricing");

        lbAdult.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lbAdult.setForeground(new java.awt.Color(255, 255, 255));
        lbAdult.setText("Adult");

        lbChild.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lbChild.setForeground(new java.awt.Color(255, 255, 255));
        lbChild.setText("Child");

        lbSnack.setFont(new java.awt.Font("Constantia", 3, 18)); // NOI18N
        lbSnack.setForeground(new java.awt.Color(255, 0, 0));
        lbSnack.setText("Snack & Drink");

        lbAdultPrice.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        lbAdultPrice.setForeground(new java.awt.Color(255, 255, 255));
        lbAdultPrice.setText("Rs 200");

        lbChildprice.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        lbChildprice.setForeground(new java.awt.Color(255, 255, 255));
        lbChildprice.setText("Rs. 150");

        lbAdultQty.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lbAdultQty.setForeground(new java.awt.Color(255, 204, 204));
        lbAdultQty.setText("Quantity:");

        lbChildQty.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lbChildQty.setForeground(new java.awt.Color(255, 204, 204));
        lbChildQty.setText("Quantity:");

        cmbAdult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cmbAdult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAdultActionPerformed(evt);
            }
        });

        cmbChild.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cmbChild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChildActionPerformed(evt);
            }
        });

        cmbsnack.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        cmbsnack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PopCorn", "Cheese PopCorn", "Fries", "Periperi Fries" }));

        cmbDrink.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        cmbDrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "coke", "Mirinda", "mazza", "Pepsie", " ", " " }));

        lbsnackQty.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lbsnackQty.setForeground(new java.awt.Color(255, 102, 102));
        lbsnackQty.setText("Quantity:");

        lbdrinkQty.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lbdrinkQty.setForeground(new java.awt.Color(255, 102, 102));
        lbdrinkQty.setText("Quantity:");

        cmbSnack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        cmbDrinkCmd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        lbTotalSnackAmt.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        lbTotalSnackAmt.setForeground(new java.awt.Color(255, 102, 102));
        lbTotalSnackAmt.setText("Rs.  000.0");

        lbExtra.setFont(new java.awt.Font("Constantia", 3, 18)); // NOI18N
        lbExtra.setForeground(new java.awt.Color(255, 0, 0));
        lbExtra.setText("Extra Service");

        lbSeattype.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        lbSeattype.setForeground(new java.awt.Color(255, 102, 102));
        lbSeattype.setText("Seat Type:");

        cmdSeat.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        cmdSeat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Premium", "Local" }));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lbAgeRate.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        lbAgeRate.setForeground(new java.awt.Color(255, 255, 255));
        lbAgeRate.setText("Age Rating:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rating");

        jLabel2.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("000");

        lbDialoug.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbDialoug.setForeground(new java.awt.Color(255, 204, 204));
        lbDialoug.setText("would you like to pay by Cash,Card or Upi");

        cmbPayment.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        cmbPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card", "Upi" }));
        cmbPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaymentActionPerformed(evt);
            }
        });

        payBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        payBtn.setText("Place A Order");
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });

        lbtheaterno.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        lbtheaterno.setForeground(new java.awt.Color(255, 204, 204));

        SubTotal.setText("Sub Total");
        SubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTotalActionPerformed(evt);
            }
        });

        Totalamt.setBackground(new java.awt.Color(255, 255, 255));
        Totalamt.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        Totalamt.setForeground(new java.awt.Color(255, 255, 255));
        Totalamt.setText("Rs .000");

        jButton1.setText("SubTotal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jButton2.setText("Total Amount To Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblMovieImage.setText("jLabel3");
        lblMovieImage.setOpaque(true);

        javax.swing.GroupLayout SubTotal2Layout = new javax.swing.GroupLayout(SubTotal2);
        SubTotal2.setLayout(SubTotal2Layout);
        SubTotal2Layout.setHorizontalGroup(
            SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubTotal2Layout.createSequentialGroup()
                .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubTotal2Layout.createSequentialGroup()
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SubTotal2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubTotal2Layout.createSequentialGroup()
                                            .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(SubTotal2Layout.createSequentialGroup()
                                                    .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(cmbsnack, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cmbDrink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(18, 18, 18))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubTotal2Layout.createSequentialGroup()
                                                    .addComponent(jButton1)
                                                    .addGap(44, 44, 44)))
                                            .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbdrinkQty)
                                                .addComponent(lbsnackQty)
                                                .addComponent(lbTotalSnackAmt))
                                            .addGap(55, 55, 55)
                                            .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cmbDrinkCmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmbSnack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(54, 54, 54))
                                        .addGroup(SubTotal2Layout.createSequentialGroup()
                                            .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(SubTotal2Layout.createSequentialGroup()
                                                    .addComponent(lbTime)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SubTotal2Layout.createSequentialGroup()
                                                    .addComponent(lbTheater)
                                                    .addGap(24, 24, 24)))
                                            .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cmbTime, 0, 84, Short.MAX_VALUE)
                                                .addComponent(lbtheaterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(jSeparator5)
                                        .addComponent(jSeparator6)
                                        .addComponent(LbTimeDetail)
                                        .addComponent(lbDay)
                                        .addComponent(jSeparator7)
                                        .addGroup(SubTotal2Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(SubTotal2Layout.createSequentialGroup()
                                                    .addComponent(lbAdult)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lbAdultPrice)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lbAdultQty))
                                                .addGroup(SubTotal2Layout.createSequentialGroup()
                                                    .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(SubTotal)
                                                        .addGroup(SubTotal2Layout.createSequentialGroup()
                                                            .addComponent(lbChild)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(lbChildprice)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(SubTotal2Layout.createSequentialGroup()
                                                            .addGap(6, 6, 6)
                                                            .addComponent(Totalamt))
                                                        .addComponent(lbChildQty))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cmbAdult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmbChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(134, 134, 134)))
                                    .addComponent(lbTicketPrice)
                                    .addComponent(lbSnack)))
                            .addGroup(SubTotal2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbLanguage)
                                    .addGroup(SubTotal2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lbMovie)))
                                .addGap(27, 27, 27)
                                .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbMovie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbLang, 0, 261, Short.MAX_VALUE))))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(SubTotal2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbCinemaName, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubTotal2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbAgeRate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(payBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SubTotal2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDialoug, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SubTotal2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SubTotal2Layout.createSequentialGroup()
                            .addComponent(lbSeattype)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmdSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lbExtra, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1))
                    .addGroup(SubTotal2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbFilmImg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMovieImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SubTotal2Layout.setVerticalGroup(
            SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubTotal2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbCinemaName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubTotal2Layout.createSequentialGroup()
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbFilmImg, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SubTotal2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblMovieImage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAgeRate)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(lbExtra)
                        .addGap(10, 10, 10)
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSeattype))
                        .addGap(11, 11, 11)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDialoug, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(payBtn))
                    .addGroup(SubTotal2Layout.createSequentialGroup()
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLanguage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(LbTimeDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTime)
                            .addComponent(cmbTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTheater)
                            .addComponent(lbtheaterno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTicketPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAdult)
                            .addComponent(lbAdultPrice)
                            .addComponent(lbAdultQty)
                            .addComponent(cmbAdult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbChild)
                            .addComponent(lbChildprice)
                            .addComponent(lbChildQty)
                            .addComponent(cmbChild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubTotal)
                            .addComponent(Totalamt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbSnack)
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SubTotal2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cmbSnack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbDrinkCmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SubTotal2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbsnack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbsnackQty))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbdrinkQty))))
                        .addGap(12, 12, 12)
                        .addGroup(SubTotal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(lbTotalSnackAmt)))
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(SubTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 791, 700));

        lbbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviebooking/bg1.jpg"))); // NOI18N
        getContentPane().add(lbbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, -64, 810, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbChildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChildActionPerformed

    }//GEN-LAST:event_cmbChildActionPerformed

    private void cmbAdultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAdultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAdultActionPerformed

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        
            new EndPage().setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_payBtnActionPerformed

    private void cmbLangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLangActionPerformed
        try
        {
        if(cmbLang.getSelectedItem().equals("English"))
        {
            cmbMovie.removeAllItems();
            cmbMovie.addItem(null);
            cmbMovie.addItem("The Shining");
            cmbMovie.addItem("Madame Web");
            cmbMovie.addItem("Land Of Bad");
        }
        else
        if(cmbLang.getSelectedItem().equals("Hindi"))
        {
            cmbMovie.removeAllItems();
            cmbMovie.addItem(null);
            cmbMovie.addItem("Fighter");
            cmbMovie.addItem("Teri Baaton Mein Aisa Uljha Jiya");
            cmbMovie.addItem("Kuch khatta Ho Jaay");
        }
        else
        if(cmbLang.getSelectedItem().equals("Marathi"))
        {
            cmbMovie.removeAllItems();
            cmbMovie.addItem(null);
            cmbMovie.addItem("Baipan Bhaari Deva");
            cmbMovie.addItem("Naal 2");
            cmbMovie.addItem("Shivrayancha Chhava");
        }
    }
    catch(Exception e)   
    {
        System.out.println(e);
    }
    }//GEN-LAST:event_cmbLangActionPerformed

    private void cmbMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMovieActionPerformed
        try
        {
        if (cmbMovie.getSelectedItem().equals("The Shining")){
            lbtheaterno.setText("CH002477");
            jLabel1.setText("R");
            cmbTime.removeAllItems();
            cmbTime.addItem("10:30am");
            cmbTime.addItem("4:00pm");
            cmbTime.addItem("6:00pm");
        }
        else
        if (cmbMovie.getSelectedItem().equals("Madame Web")){
            lbtheaterno.setText("CH002435");
            jLabel1.setText("PG-13");
            cmbTime.removeAllItems();
            cmbTime.addItem("10:30am");
            cmbTime.addItem("4:00pm");
            cmbTime.addItem("6:00pm");
        }    
        else
        if (cmbMovie.getSelectedItem().equals("Land Of Bad")){
            lbtheaterno.setText("CH002436");
            jLabel1.setText("R");
            cmbTime.removeAllItems();
            cmbTime.addItem("10:30am");
            cmbTime.addItem("4:00pm");
            cmbTime.addItem("6:00pm");
        }   
        else
            if (cmbMovie.getSelectedItem().equals("Fighter")){
            lbtheaterno.setText("CH00277");
            jLabel1.setText("15A");
            cmbTime.removeAllItems();            
            cmbTime.addItem("12:30am");
            cmbTime.addItem("9:00pm");
            cmbTime.addItem("8:00am");
        }   
        else
        if (cmbMovie.getSelectedItem().equals("Teri Baaton Mein Aisa Uljha Jiya")){
            lbtheaterno.setText("CH002466");
            jLabel1.setText("PG-13");
            cmbTime.removeAllItems();
            cmbTime.addItem("10:30am");
            cmbTime.addItem("4:00pm");
            cmbTime.addItem("6:00pm");
        }  
        else
        if (cmbMovie.getSelectedItem().equals("Kuch khatta Ho Jaay")){
            lbtheaterno.setText("CH002422");
            jLabel1.setText("UA");
            cmbTime.removeAllItems();
            cmbTime.addItem("10:30am");
            cmbTime.addItem("4:00pm");
            cmbTime.addItem("6:00pm");
        } 
        else
        if (cmbMovie.getSelectedItem().equals("Baipan Bhaari Deva")){
            lbtheaterno.setText("CH002466");
            jLabel1.setText("Not Rated(USA)");
            cmbTime.removeAllItems();
            cmbTime.addItem("12:30am");
            cmbTime.addItem("9:00pm");
            cmbTime.addItem("8:00am");
            
        }
        else
        if (cmbMovie.getSelectedItem().equals("Naal 2")){
            lbtheaterno.setText("CH002435");
            jLabel1.setText("12A");
            cmbTime.removeAllItems();
             cmbTime.addItem("12:30am");
            cmbTime.addItem("9:00pm");
            cmbTime.addItem("8:00am");
        }
        else
        if (cmbMovie.getSelectedItem().equals("Shivrayancha Chhava")){
            lbtheaterno.setText("CH002422");
            jLabel1.setText("15A");
            cmbTime.removeAllItems();
            cmbTime.addItem("12:30am");
            cmbTime.addItem("9:00pm");
            cmbTime.addItem("8:00am");
        }
        else
        if (cmbMovie.getSelectedItem().equals("Kuch Khatta Ho Jaay")){
            lbtheaterno.setText("CH002455");
            jLabel1.setText("UA");
             cmbTime.addItem("12:30am");
            cmbTime.addItem("9:00pm");
            cmbTime.addItem("8:00am");
        }
         // ✅ Show selected movie image in lblMovieImage
        try {
            String selectedMovie = cmbMovie.getSelectedItem().toString();
            String imageName = selectedMovie.replaceAll(" ", "") + ".jpg";  // e.g., "MadameWeb.jpg"
            String imagePath = "/moviebooking/" + imageName;  // Assuming images are in 'moviebooking' package

            ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
            Image img = icon.getImage().getScaledInstance(lblMovieImage.getWidth(), lblMovieImage.getHeight(), Image.SCALE_SMOOTH);
            lblMovieImage.setIcon(new ImageIcon(img));
        } catch (Exception ex) {
            lblMovieImage.setIcon(null);
            System.out.println("Image not found: " + ex.getMessage());
        }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_cmbMovieActionPerformed

    private void cmbPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaymentActionPerformed
        if(cmbPayment.getSelectedItem().equals("Cash"))
        {
           try
           {
               String cashEntered= jOptionPane1.showInputDialog(null,"Please Enter the Cash Paid:","Cash Payment",jOptionPane1.OK_CANCEL_OPTION);
               double CashPaid= Double.parseDouble(cashEntered);
           }
           catch(NumberFormatException | NullPointerException e)
                   {
                      jOptionPane1.showMessageDialog(null,"Please enter number only");
                      payBtn.setEnabled(false);
                   }
        }
        if(cmbPayment.getSelectedItem().equals("Card"))
        {
            try
            {
                String cardDetails= jOptionPane1.showInputDialog(null,"Please Enter Card Detail","Card Payment",jOptionPane1.OK_CANCEL_OPTION);
                if(!cardDetails.isEmpty()){
                    payBtn.setEnabled(true);
                    //disableEverythingActionPerformed(evt);
                }
            }catch(NullPointerException e){
                       payBtn.setEnabled(false);
                       }
        }
        if(cmbPayment.getSelectedItem().equals("Upi"))
        {
           try
           {
               String UPI= jOptionPane1.showInputDialog(null,"Please Enter the Your Upi Id:","UPI Payment",jOptionPane1.OK_CANCEL_OPTION);
               double UPIPAID= Double.parseDouble(UPI);
                if(!UPI.isEmpty()){
                    payBtn.setEnabled(true);
                }
           }
           catch(NullPointerException e)
                   {
                      jOptionPane1.showMessageDialog(null,"Please enternumber only");
                      payBtn.setEnabled(false);
                   }
        }
    }//GEN-LAST:event_cmbPaymentActionPerformed

    private void SubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTotalActionPerformed
        int child= Integer.parseInt((String) cmbChild.getSelectedItem());;
        int adult = Integer.parseInt((String) cmbAdult.getSelectedItem());
        int total = 150 * child + adult * 200;
        Totalamt.setText("Rs."+String.valueOf(total));
    }//GEN-LAST:event_SubTotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int Drink= Integer.parseInt((String) cmbDrinkCmd.getSelectedItem());
        int Snack= Integer.parseInt((String) cmbSnack.getSelectedItem());
        int total = 100 * Drink + Snack * 120;
        lbTotalSnackAmt.setText("Rs."+String.valueOf(total));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int child= Integer.parseInt((String) cmbChild.getSelectedItem());;
        int adult = Integer.parseInt((String) cmbAdult.getSelectedItem());
        int Drink= Integer.parseInt((String) cmbDrinkCmd.getSelectedItem());
        int Snack= Integer.parseInt((String) cmbSnack.getSelectedItem());
        double totaltopay= child * 150 + adult * 200 + Drink * 100 + Snack * 120;
        //String strTotal= Double.toString(totaltopay);
        jLabel2.setText("Rs."+String.valueOf(totaltopay));


    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new HomePage().setVisible(true);  // this shows the GUI
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbTimeDetail;
    private javax.swing.JButton SubTotal;
    private javax.swing.JPanel SubTotal2;
    private javax.swing.JLabel Totalamt;
    private javax.swing.JComboBox<String> cmbAdult;
    private javax.swing.JComboBox<String> cmbChild;
    private javax.swing.JComboBox<String> cmbDrink;
    private javax.swing.JComboBox<String> cmbDrinkCmd;
    private javax.swing.JComboBox<String> cmbLang;
    private javax.swing.JComboBox<String> cmbMovie;
    private javax.swing.JComboBox<String> cmbPayment;
    private javax.swing.JComboBox<String> cmbSnack;
    private javax.swing.JComboBox<String> cmbTime;
    private javax.swing.JComboBox<String> cmbsnack;
    private javax.swing.JComboBox<String> cmdSeat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbAdult;
    private javax.swing.JLabel lbAdultPrice;
    private javax.swing.JLabel lbAdultQty;
    private javax.swing.JLabel lbAgeRate;
    private javax.swing.JLabel lbChild;
    private javax.swing.JLabel lbChildQty;
    private javax.swing.JLabel lbChildprice;
    private javax.swing.JLabel lbCinemaName;
    private javax.swing.JLabel lbDay;
    private javax.swing.JLabel lbDialoug;
    private javax.swing.JLabel lbExtra;
    private javax.swing.JLabel lbFilmImg;
    private javax.swing.JLabel lbLanguage;
    private javax.swing.JLabel lbMovie;
    private javax.swing.JLabel lbSeattype;
    private javax.swing.JLabel lbSnack;
    private javax.swing.JLabel lbTheater;
    private javax.swing.JLabel lbTicketPrice;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel lbTotalSnackAmt;
    private javax.swing.JLabel lbbackground;
    private javax.swing.JLabel lbdrinkQty;
    private javax.swing.JLabel lblMovieImage;
    private javax.swing.JLabel lbsnackQty;
    private javax.swing.JLabel lbtheaterno;
    private javax.swing.JButton payBtn;
    // End of variables declaration//GEN-END:variables
}
